version: '2'

services:
    app:
      build: .
      environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ports:
        - '8080:3000'
      volumes:
        - .:/opt/app
      networks:
          - default
          - app
      command:
        - /bin/sh
        - -c
        - |
            sls offline

networks:
    default:
    app:
        external: true
